contacts.update(
{'tsstuff-admin': {'alias': u'tsstuff-admin',
                    'contactgroups': ['tsstuff-admins'],
                    'disable_notifications': False,
                    'email': 'tsstuff-noc@techsquare.com',
                    'pager': ''},
 'tsstuff-pager': {'alias': u'tsstuff-pager',
                    'contactgroups': ['tsstuff-pager'],
                    'disable_notifications': False,
                    'email': 'tsstuff-page@techsquare.com',
                    'pager': ''},
 'tsstuff-view': {'alias': u'tsstuff view',
                   'contactgroups': [],
                   'disable_notifications': False,
                   'email': '',
                   'pager': ''},
 'machineuser': {'alias': u'machine',
                 'contactgroups': [],
                 'disable_notifications': False},
 'omdadmin': {'alias': u'omdadmin',
              'contactgroups': [],
              'disable_notifications': False,
              'email': '',
              'pager': ''}}
)

