notification_rules += [{'allow_disable': True,
  'comment': u'basic host first two emails\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'basic host first 2 emails, one per hour',
  'disabled': False,
  'match_escalation': (1, 2),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-basic'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST: $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'basic host escalation emails,send daily\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'host basic escalation emails, send daily during work hours',
  'disabled': False,
  'match_escalation': (3, 999999),
  'match_escalation_throttle': (1, 24),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-basic'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:$HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'sends email from the second notification at regular one hour intervals\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'host critical email overnights',
  'disabled': False,
  'match_escalation': (1, 99999),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-critical'],
  'match_timeperiod': 'overnight',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:  $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'sends email from the second notification at regular one hour intervals\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'host critical send email first email no page',
  'disabled': False,
  'match_escalation': (1, 1),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-critical'],
  'match_timeperiod': 'workhours',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:  $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'critical host escalation page, hourly after second notification\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-pager'],
  'contact_object': False,
  'description': u'host critical pager',
  'disabled': False,
  'match_escalation': (2, 9999),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-critical'],
  'match_timeperiod': 'workhours',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:  $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'critical host 24x7 escalation email\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'host critical 24x7 send email',
  'disabled': False,
  'match_escalation': (1, 1),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-critical-24x7'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:  $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'critical host escalation page\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-pager'],
  'contact_object': False,
  'description': u'host critical 24x7 pager',
  'disabled': False,
  'match_escalation': (2, 9999),
  'match_host_event': ['rd', 'dr', 'ru', 'du', 'ud', 'ur', 'f', 's', 'x'],
  'match_hostgroups': ['tsstuff-critical-24x7'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'host_subject': u'TSSTUFF-NOC-HOST:  $HOSTNAME$ - $EVENT_TXT$',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n'})},
 {'allow_disable': True,
  'comment': u'basic service escalation email\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'basic service send first two emails hourly',
  'disabled': False,
  'match_escalation': (1, 2),
  'match_hostgroups': ['tsstuff-basic'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE:  $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'basic service escalation email\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'service basic daily email after first 2 hours',
  'disabled': False,
  'match_escalation': (3, 999999),
  'match_escalation_throttle': (1, 5),
  'match_hostgroups': ['tsstuff-basic'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'critical service escalation email\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'service critical email overnights',
  'disabled': False,
  'match_escalation': (1, 99999),
  'match_exclude_services': [u'Check_MK'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'match_servicegroups': ['tsstuff-critical'],
  'match_timeperiod': 'overnight',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'critical service escalation email\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'service critical first email no page',
  'disabled': False,
  'match_escalation': (1, 1),
  'match_exclude_services': [u'Check_MK'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'match_servicegroups': ['tsstuff-critical'],
  'match_timeperiod': 'workhours',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'critical service hourly page\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-pager'],
  'contact_object': False,
  'description': u'service critical pager',
  'disabled': False,
  'match_escalation': (2, 9999),
  'match_exclude_services': [u'Check_MK'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'match_servicegroups': ['tsstuff-critical'],
  'match_timeperiod': 'workhours',
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'critical 24x7 service hourly email \n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-admins'],
  'contact_object': False,
  'description': u'service critical 24x7 email',
  'disabled': False,
  'match_escalation': (1, 1),
  'match_exclude_services': [u'Check_MK'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'match_servicegroups': ['tsstuff-critical-24x7'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'critical 24x7 service pager, sends once hourly after second notification\n',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_groups': ['tsstuff-pager'],
  'contact_object': False,
  'description': u'service critical 24x7 pager',
  'disabled': False,
  'match_escalation': (2, 9999),
  'match_exclude_services': [u'Check_MK'],
  'match_service_event': ['rw',
                          'rc',
                          'ru',
                          'wr',
                          'wc',
                          'wu',
                          'cr',
                          'cw',
                          'cu',
                          'ur',
                          'uw',
                          'uc',
                          'f',
                          's',
                          'x'],
  'match_servicegroups': ['tsstuff-critical-24x7'],
  'notify_plugin': ('asciimail',
                    {'common_body': u'Host:     $HOSTNAME$\n',
                     'from': 'tsstuff-noc@techsquare.com',
                     'host_body': u'Event:    $EVENT_TXT$\nOutput:   $HOSTOUTPUT$\nPerfdata: $HOSTPERFDATA$\n$LONGHOSTOUTPUT$\n',
                     'reply_to': 'tsstuff-noc@techsquare.com',
                     'service_body': u'Service:  $SERVICEDESC$\nEvent:    $EVENT_TXT$\nOutput:   $SERVICEOUTPUT$\nPerfdata: $SERVICEPERFDATA$\n$LONGSERVICEOUTPUT$\n',
                     'service_subject': u'TSSTUFF-NOC-SERVICE: $HOSTNAME$/$SERVICEDESC$ $EVENT_TXT$'})},
 {'allow_disable': True,
  'comment': u'',
  'contact_all': False,
  'contact_all_with_email': False,
  'contact_object': True,
  'description': u'Notify all contacts of a host/service via HTML email',
  'disabled': True,
  'notify_plugin': ('mail', {})}]

