#!/bin/bash
contract=eaps
site=eapsnoc
sed "s/tsstuff/$contract/g" contacts.mk > /omd/sites/$site/etc/check_mk/conf.d/wato/contacts.mk 
sed "s/tsstuff/$contract/g" checks.mk > /omd/sites/$site/etc/check_mk/conf.d/wato/checks.mk
sed "s/tsstuff/$contract/g" groups.mk > /omd/sites/$site/etc/check_mk/conf.d/wato/groups.mk
sed "s/tsstuff/$contract/g" multisite.mk > /omd/sites/$site/etc/check_mk/multisite.mka
sed -i "s/tsstuff/$contract/g" notifications.mk
sed -i "s/TSSTUFF/${contract^^}/g" notifications.mk
sed "s/tsstuff/$contract/g" notifications.mk > /omd/sites/$site/etc/check_mk/conf.d/wato/notifications.mk
sed "s/tsstuff/$contract/g" rules.mk > /omd/sites/$site/etc/check_mk/conf.d/wato/rules.mk
sed "s/tsstuff/$contract/g" users.mk > /omd/sites/$site/etc/check_mk/multisite.d/wato/users.mk
cp timeperiods.mk /omd/sites/$site/etc/check_mk/conf.d/wato/timeperiods.mk

